"""Add is_active and inactivated_on fields to User

Revision ID: 85fcad094aee
Revises: bc00a2b343b6
Create Date: 2024-10-15 07:55:07.863439

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "85fcad094aee"
down_revision = "bc00a2b343b6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_active", sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column("inactivated_on", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("inactivated_on")
        batch_op.drop_column("is_active")

    # ### end Alembic commands ###
