"""Change status column from boolean to string

Revision ID: dcfa167aa33c
Revises: d7cc877e7cf0
Create Date: 2024-10-15 09:32:20.240064

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dcfa167aa33c"
down_revision = "d7cc877e7cf0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users_active_status_changes", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=sa.BOOLEAN(),
            type_=sa.String(length=10),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users_active_status_changes", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=sa.String(length=10),
            type_=sa.BOOLEAN(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
